name = "idolformationmaker"
compatibility_date = "2024-12-25"
main = "worker/index.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
API_URL = "https://combining-introductory-removable-update.trycloudflare.com"
